import { spawn } from 'node:child_process'
import { createHash } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'

export const PACK_SCHEMA = 'agentic-graph.workspace-program-pack/v1'
export const PACK_TOOL = 'commerce.workspace.program-pack.create'
export const PACK_LIMITS = Object.freeze({ requestBytes: 98304, sourceBytes: 32768, resultBytes: 225280, deadlineMs: 5000 })
export type PackRequest = Readonly<{ title: string; source: string; sourceDigest: string }>
export type PackFile = Readonly<{ name: string; mediaType: string; content: string; bytes: number; digest: string }>
export type PackResult = Readonly<{ schema: string; owner: string; languageProfile: string; title: string;
  sourceDigest: string; execution: string; roundTrip: string; canvas: { format: string; nodes: number; edges: number };
  files: readonly PackFile[]; artifactDigest: string }>
export const digest = (value: string | Buffer) => createHash('sha256').update(value).digest('hex')
const record = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value)
const exact = (value: Record<string, unknown>, keys: string) => Object.keys(value).sort().join(',') === keys

export function readPackRequest(value: unknown): PackRequest {
  if (!record(value) || !exact(value, 'source,sourceDigest,title') || typeof value.source !== 'string'
    || !value.source.trim() || Buffer.byteLength(value.source) > PACK_LIMITS.sourceBytes
    || typeof value.title !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9 ._-]{0,79}$/.test(value.title)
    || typeof value.sourceDigest !== 'string' || value.sourceDigest !== digest(value.source)) {
    throw Error('workspace_pack_input_invalid_or_stale')
  }
  return { title: value.title, source: value.source, sourceDigest: value.sourceDigest }
}

/** Strict protocol reader. Commerce owns the offer; Graph owns every generated byte. */
export function readPackResult(text: string, input: PackRequest): PackResult {
  if (Buffer.byteLength(text) > PACK_LIMITS.resultBytes + 1) throw Error('workspace_pack_result_limit')
  const value: unknown = JSON.parse(text)
  if (!record(value) || !exact(value, 'artifactDigest,canvas,execution,files,languageProfile,owner,roundTrip,schema,sourceDigest,title')
    || value.schema !== PACK_SCHEMA || value.owner !== 'agentic-graph' || value.languageProfile !== 'procedural-python/v1'
    || value.title !== input.title || value.sourceDigest !== input.sourceDigest || value.execution !== 'not-executed'
    || value.roundTrip !== 'exact' || !record(value.canvas) || !exact(value.canvas, 'edges,format,nodes')
    || value.canvas.format !== 'mermaid' || !Number.isInteger(value.canvas.nodes) || Number(value.canvas.nodes) < 1
    || Number(value.canvas.nodes) > 256 || value.canvas.edges !== Number(value.canvas.nodes) - 1
    || !Array.isArray(value.files) || value.files.length !== 4) throw Error('workspace_pack_result_invalid')
  const names = ['program.py', 'program.json', 'program.md', 'canvas.md']
  const types = ['text/x-python', 'application/json', 'text/markdown', 'text/markdown']
  value.files.forEach((file: unknown, index) => {
    if (!record(file) || !exact(file, 'bytes,content,digest,mediaType,name') || file.name !== names[index]
      || file.mediaType !== types[index] || typeof file.content !== 'string'
      || file.bytes !== Buffer.byteLength(file.content) || file.digest !== digest(file.content)) throw Error('workspace_pack_file_invalid')
  })
  if (value.files[0].content !== input.source) throw Error('workspace_pack_source_changed')
  const { artifactDigest, ...unsigned } = value
  if (artifactDigest !== digest(JSON.stringify(unsigned))) throw Error('workspace_pack_digest_invalid')
  return value as unknown as PackResult
}

export function createGraphPackAdapter(file: string, expectedDigest: string) {
  if (!path.isAbsolute(file) || !/^[a-f0-9]{64}$/.test(expectedDigest)) throw Error('workspace_pack_adapter_configuration_required')
  const fd = fs.openSync(file, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW)
  let source: string
  try {
    const stat = fs.fstatSync(fd)
    if (!stat.isFile() || stat.size >= 500000) throw Error('workspace_pack_adapter_size')
    source = fs.readFileSync(fd, 'utf8')
    if (Buffer.byteLength(source) >= 500000 || digest(source) !== expectedDigest) throw Error('workspace_pack_adapter_identity')
  } finally { fs.closeSync(fd) }
  // Execute the verified immutable bytes, avoiding a second path read after the digest check.
  const moduleUrl = `data:text/javascript;base64,${Buffer.from(source).toString('base64')}`
  return async (raw: unknown, signal: AbortSignal): Promise<PackResult> => {
    const input = readPackRequest(raw)
    if (signal.aborted) throw Error('workspace_pack_cancelled')
    return new Promise((resolve, reject) => {
      // Worker type generation augments ProcessEnv; this Node child deliberately inherits no environment.
      const child = spawn(process.execPath, ['--max-old-space-size=96', '--input-type=module', '-e', 'await import(process.argv[1])', moduleUrl],
        { env: {} as NodeJS.ProcessEnv, stdio: ['pipe', 'pipe', 'pipe'] })
      let output = '', failure = '', bytes = 0, cause = ''
      const stop = (code: string) => { cause ||= code; child.kill('SIGKILL') }
      const abort = () => stop('workspace_pack_cancelled')
      const timer = setTimeout(() => stop('workspace_pack_deadline'), PACK_LIMITS.deadlineMs)
      signal.addEventListener('abort', abort, { once: true })
      child.stdout.setEncoding('utf8'); child.stderr.setEncoding('utf8')
      child.stdout.on('data', (chunk: string) => {
        bytes += Buffer.byteLength(chunk)
        if (bytes > PACK_LIMITS.resultBytes + 1) stop('workspace_pack_result_limit')
        else output += chunk
      })
      child.stderr.on('data', (chunk: string) => { if (failure.length < 256) failure += chunk.slice(0, 256 - failure.length) })
      child.stdin.on('error', () => { /* close/error owns the final outcome */ })
      child.once('error', () => { cause = 'workspace_pack_adapter_unavailable' })
      child.once('close', code => {
        clearTimeout(timer); signal.removeEventListener('abort', abort)
        if (cause || code !== 0) { reject(Error(cause || (/^workspace_pack_[a-z_]+\n?$/.test(failure)
          ? failure.trim() : 'workspace_pack_conversion_refused'))); return }
        try { resolve(readPackResult(output, input)) } catch (error) { reject(error) }
      })
      child.stdin.end(JSON.stringify({ schema: PACK_SCHEMA, ...input }))
      if (signal.aborted) abort()
    })
  }
}
