/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.sandbox.jsonc --env=production --include-runtime=false --strict-vars=false --env-interface=DeviceSandboxEnv src/sandbox/device-env.d.ts` (hash: f5d5979caec62802f9aac8e5bf2d8c0b)
interface __BaseEnv_DeviceSandboxEnv {
	CF_VERSION_METADATA: WorkerVersionMetadata;
	DEPLOY_LANE: string;
	RELEASE_CANDIDATE_SHA: string;
	RELEASE_CANDIDATE_DIGEST: string;
	EXECUTION_HOST_URL: string;
	EXECUTION_HOST_BUNDLE_SHA256: string;
	EXECUTION_HOST_IMAGE_ID: string;
	EXECUTION_HOST_BEARER_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./device-executor");
	}
	interface Env extends __BaseEnv_DeviceSandboxEnv {}
}
interface DeviceSandboxEnv extends __BaseEnv_DeviceSandboxEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOY_LANE" | "RELEASE_CANDIDATE_SHA" | "RELEASE_CANDIDATE_DIGEST" | "EXECUTION_HOST_URL" | "EXECUTION_HOST_BUNDLE_SHA256" | "EXECUTION_HOST_IMAGE_ID" | "EXECUTION_HOST_BEARER_TOKEN">> {}
}
